### PR TITLE
Add new trove classifier Framework: FastAPI

### PR DESCRIPTION
**Pull request by tiangolo**
Request to add a new Trove classifier for FastAPI

## The name of the classifier(s) you would like to add:

* `Framework :: FastAPI`

## Why do you want to add this classifier?

FastAPI is a relatively recent web framework. It is, in some sense, comparable to Flask and Django (that have trove classifiers).

By the latest [Python developer survey](https://www.jetbrains.com/lp/python-developers-survey-2020/) it seems it's currently the 3rd most used Python web framework, after Flask and Django.

Also by the latest [StackOverflow Developer Survey](https://insights.stackoverflow.com/survey/2021#section-most-loved-dreaded-and-wanted-web-frameworks) it's the 3rd most loved web framework, in a category that combines frontend and backend in all the languages. Putting FastAPI right on top of React and Vue.js. 🎉

Given the current adoption and the number of new projects and third-party packages being built for FastAPI (for example, [the `fastapi` topic in GitHub](https://github.com/topics/fastapi)), it would probably make sense to have a trove classifier for it.

This would close https://github.com/pypa/trove-classifiers/issues/63

### CODE REVIEW

**Comment by pradyunsg** [comment]
Hi! Thanks for the request. Because removing classifiers is very difficult, and the longer the classifier list gets the harder it is to browse, the bar to add new ones is relatively high. Currently, PyPI moderators primarily examine two guidelines for Framework classifiers:

- New Framework classifiers should be created if they are "notable" and
- They will be of immediate use to existing projects (in other words, no creating classifiers simply in anticipation of future uses)

I think this qualifies for both. I'll let one of the PyPI admins land this PR. :)

**Comment by pradyunsg** [comment]
> I'll let one of the PyPI admins land this PR. :)

Thinking about this for a bit, I don't think that's necessary.

**Comment by tiangolo** [comment]
Thanks @pradyunsg! ☕

**Comment by di** [comment]
FYI, the release failed here b/c this repository uses CalVer and currently can only make 1 release per day (and I had just merged/released #85 before this). Generally I try to wait ~24 hours between merges to avoid this (it's less than ideal, but it's what we've got right now).

I'll re-run the build in ~7 hours.

**Pull request merged**
