### PR TITLE
Added PySimpleGUI versions 4 and 5 as a Framework

### PR DESCRIPTION
**Pull request by PySimpleGUI**
Request to add a new Trove classifier.

## The name of the classifier(s) you would like to add:

* "Framework :: PySimpleGUI :: 4"
* "Framework :: PySimpleGUI :: 5"

## Why do you want to add this classifier?

PySimpleGUI, the popular GUI framework for Python, is about to ship a major upgrade. PySimpleGUI 5 features significant enhancements, including new features, new tools, and new support plans. PyPi users will find value in being able to distinguish between the various versions, and the best mechanism is to add distinctive classifiers.

### CODE REVIEW

**Review by timkay — APPROVED** [review]
Seems like an obvious addition, given the popularity of PySimpleGUI. Approved!

**Comment by PySimpleGUI** [comment]
Am I missing some required information?

Lemme see if this is a secret phrase as it worked for the last approved pull request.

> @di are you available to merge this easy one?

**Comment by PySimpleGUI** [comment]
Thank you very much @di!  DOH!  Sorry about the botched sort.  I think I fixed it correctly.

**Comment by PySimpleGUI** [comment]
Oops.... I'll keep trying!

**Review by di — APPROVED** [review]

**Comment by PySimpleGUI** [comment]
image

Awesome!

Thank you so much Dustin for the help!

**Comment by PySimpleGUI** [comment]
When do these changes show up on the PyPI site / become usable by packages being uploaded?

**Comment by miketheman** [comment]
> When do these changes show up on the PyPI site / become usable by packages being uploaded?

Now that they have been merged and a release containing the changes has been published, it takes a day or two for Dependabot to suggest the change to warehouse, and then it might take a few days for us to merge it in.

**Comment by di** [comment]
When the dependency gets update on PyPI, which has happened: https://github.com/pypi/warehouse/blob/d74fff4e3d89b136fec5e17c180620c9cfcef0f3/requirements/main.txt#L1628-L1631

However looks like we had a deployment failure: https://github.com/pypi/warehouse/actions/runs/6867233971/attempts/1

**Comment by di** [comment]
You should now see these classifiers here, which means they're good to use: https://pypi.org/classifiers/

**Pull request merged**
