### PR TITLE
Add classifiers for CUDA 11 / 12 / 12.0

### PR DESCRIPTION
**Pull request by leofang**
Request to add a new Trove classifier.

## The name of the classifier(s) you would like to add:

* `Environment :: GPU :: NVIDIA CUDA :: 11`
* `Environment :: GPU :: NVIDIA CUDA :: 12`
* ~~`Environment :: GPU :: NVIDIA CUDA :: 12.0`~~ **UPDATE**: `Environment :: GPU :: NVIDIA CUDA 12 :: 12.0` (see https://github.com/pypa/trove-classifiers/pull/124#issuecomment-1346951378)

## Why do you want to add this classifier?

CUDA 12.0 just came out today, so it'd be nice to add it now.

As for the major-version classifiers (CUDA 11/12), I consider them useful because starting with CUDA 11 there is guaranteed minor version compatibility at the programming model level (with caveats that users/developers would understand), so wheels can tag `CUDA :: 11` or `CUDA :: 12` to declare such compatibility. For example, NVIDIA and some GPU frameworks have been uploading wheels with suffix `-cuXX` (XX=11 currently) on PyPI.org.

cc: @jakirkham @m3vaz

### CODE REVIEW

**Comment by jakirkham** [comment]
LGTM. Thanks Leo! 🙏

**Comment by jakirkham** [comment]
cc @di

**Comment by di** [comment]
I feel like having both `12` and `12.0` will be confusing. I realize this is what we do for the Python classifiers, but there's a lot more precedent there.

Would you be opposed to:

* `Environment :: GPU :: NVIDIA CUDA :: 11`
* `Environment :: GPU :: NVIDIA CUDA :: 12`
* `Environment :: GPU :: NVIDIA CUDA :: 12 :: 12.0`

instead? Or is there another way to refer to everything compatible with a major version?

**Comment by leofang** [comment]
Thanks, Dustin. I don't have strong opinion about `Environment :: GPU :: NVIDIA CUDA :: 12.0` vs `Environment :: GPU :: NVIDIA CUDA :: 12 :: 12.0`, except that I'd note the former is following the years of established precedence. Having the extra major ver in the middle (as in `CUDA :: 12 :: 12.0`) does not seem to convey extra information.

Also, we're not changing any existing `Environment :: GPU :: NVIDIA CUDA :: 11.x` to `Environment :: GPU :: NVIDIA CUDA :: 11 :: 11.x`, right? So from this point of view, I'd argue the latter `CUDA :: 12 :: 12.0` is more confusing than the former. 

But in any case I agree that we are creating a new convention (for major-ver only classifiers). As I said I don't have strong opinion 🙂

**Comment by di** [comment]
Would this be more or less confusing in your opinion?

* `Environment :: GPU :: NVIDIA CUDA :: 11.x`
* `Environment :: GPU :: NVIDIA CUDA :: 12.x`
* `Environment :: GPU :: NVIDIA CUDA :: 12.0`

I don't feel to strongly about this, but whatever we decide will be set in stone, more or less.

**Comment by leofang** [comment]
That's interesting, I am thinking `11.x`/`12.x` are more colloquial terms and a bit uncertain if its semantics is obvious from the first glance.

> but whatever we decide will be set in stone, more or less.

Indeed. I wouldn't mind if you want to keep this PR open for a bit longer, Dustin. I can also ask NV folks internally and see if any of them has strong opinion on the 3 proposals ([this](https://github.com/pypa/trove-classifiers/pull/124#issue-1486061720), [this](https://github.com/pypa/trove-classifiers/pull/124#issuecomment-1344375281), [this](https://github.com/pypa/trove-classifiers/pull/124#issuecomment-1344403929)) on the table.

Thanks!

**Comment by leofang** [comment]
Hi @di we discussed internally briefly about this, with CUDA product management involved. The 2nd proposal is slightly preferred (though none of us has strong opinion), so I just updated the PR. PTAL 🙂 thx!

**Comment by leofang** [comment]
Friendly nudge @di 🙂

**Comment by leofang** [comment]
Another friendly nudge @di 🙂

**Comment by jakirkham** [comment]
Thanks Leo and Dustin! 🙏

**Pull request merged**
