### PR TITLE
Add jupyterlab trove classifiers

### PR DESCRIPTION
**Pull request by bollwyvl**
## The name of the classifier(s) you would like to add:

* `Framework :: Jupyter`
* `Framework :: Jupyter :: JupyterLab`
* `Framework :: Jupyter :: JupyterLab :: 1`
* `Framework :: Jupyter :: JupyterLab :: 2`
* `Framework :: Jupyter :: JupyterLab :: 3`
* `Framework :: Jupyter :: JupyterLab :: 4`
* `Framework :: Jupyter :: JupyterLab :: Extensions`
* `Framework :: Jupyter :: JupyterLab :: Extensions :: Prebuilt`
* `Framework :: Jupyter :: JupyterLab :: Extensions :: Themes`
* `Framework :: Jupyter :: JupyterLab :: Extensions :: Mime Renderers`

## Why do you want to add this classifier?

> Include a brief explanation to justify your request.

JupyterLab is the flagship client UI for the [Jupyter Project](https://jupyter.org). The core package appears to have [million or so](https://pypistats.org/packages/jupyterlab) monthly downloads from PyPI, as well as millions of historical downloads from [other package managers](https://anaconda.org/conda-forge/jupyterlab).

> Why do the current classifiers not meet your need?

While JupyterLab is the flagship UI, many other open source and proprietary offerings also implement (parts of) the Jupyter protocols. Having versioned, JupyterLab-specific classifiers will help users navigate this sometimes bewildering landscape, both within the python community and beyond.

> How many projects do you expect to use this new classifier?

[~700 packages](https://pypi.org/search/?q=jupyterlab) presently mention JupyterLab. 

> If you are requesting multiple classifiers, why do you need more than one?

As a highly extensible, fast-moving project which delivers interactive computing for learning and (data) science, we have a number of active major version lines which continue to receive security and bugfix releases.

For the variety of extensions, for which these classifiers are mostly intended, we maintain [a](https://github.com/jupyterlab/extension-cookiecutter-ts) [couple](https://github.com/jupyter-widgets/widget-ts-cookiecutter) [cookiecutters](https://github.com/jupyterlab/theme-cookiecutter) and would pre-seed new packages with these classifiers.

Finally, the `Prebuilt` classifier will help users determine whether `pip install some-extension` should _Just Work_, often without restarting the underlying python server.

## References
- first-party developer documentation [draft PR](https://github.com/jupyterlab/jupyterlab/pull/10731)

Thanks! :heart:

### CODE REVIEW

**Comment by di** [comment]
Thanks for the PR, just an FYI that CI is failing because these are not sorted.

Could you give us more detail about what the `Framework :: Jupyter :: JupyterLab :: Extensions :: Themes` and
`Framework :: Jupyter :: JupyterLab :: Extensions :: Mime Renderers` classifiers are for?

**Comment by krassowski** [comment]
Let me quote our docs:

A JupyterLab plugin is the basic unit of extensibility in JupyterLab. JupyterLab supports several types of plugins:

- Application plugins: Application plugins are the fundamental building block of JupyterLab functionality. Application plugins interact with JupyterLab and other plugins by requiring services provided by other plugins, and optionally providing their own service to the system. Application plugins in core JupyterLab include the main menu system, the file browser, and the notebook, console, and file editor components.

- Mime renderer plugins: Mime renderer plugins are simplified, restricted ways to extend JupyterLab to render custom mime data in notebooks and files. These plugins are automatically converted to equivalent application plugins by JupyterLab when they are loaded. Examples of mime renderer plugins that come in core JupyterLab are the pdf viewer, the JSON viewer, and the Vega viewer.

    Examples include:
    - https://pypi.org/project/jupyterlab-mathjax3/
    - https://pypi.org/project/jupyterlab-vega3/
    - https://pypi.org/project/jupyterlab-fasta/
    - https://pypi.org/project/jupyterlab-geojson/

- Theme plugins: Theme plugins provide a way to customize the appearance of JupyterLab by changing themeable values (i.e., CSS variable values) and providing additional fonts and graphics to JupyterLab. JupyterLab comes with light and dark theme plugins.

    Examples include:
    - https://pypi.org/project/theme-darcula/
    - https://pypi.org/project/jupyterlab-theme-minimalist/
    - https://pypi.org/project/jupyterlab-theme-hale/
    - https://pypi.org/project/jupyterlab-simpledark/

**Comment by di** [comment]
Thanks! This project is released automatically every 24 hours if there are changes, after which we'll need to pull the new version into PyPI itself before these are available. I'll let you know here once that happens.

**Comment by bollwyvl** [comment]
Many thanks!

**Comment by bollwyvl** [comment]
> I'll let you know here once that happens.

Any update?

**Comment by di** [comment]
Here's the PR: https://github.com/pypa/warehouse/pull/9882

You can follow that or wait for my update here once it's merged.

**Comment by di** [comment]
The PR is merged and this is available now.

**Pull request merged**
