### PR TITLE
Add `Environment :: WebAssembly` classifiers

### PR DESCRIPTION
**Pull request by brettcannon**
Request to add a new Trove classifier.

## The name of the classifier(s) you would like to add:

* `Environment :: WebAssembly`
* `Environment :: WebAssembly :: Emscripten`
* `Environment :: WebAssembly :: WASI`

## Why do you want to add this classifier?

To have a way for projects to mark that they are compatible with WebAssembly via their pure Python wheels, and specifically with either Emscripten or WASI-based WebAssembly runtimes (see [my blog post on WebAssembly and its platforms](https://snarky.ca/webassembly-and-its-platform-targets/) for what those two platforms represent).

I almost requested under "Topic" instead of "Environment", but since I'm hoping these will be used to mark a project is compatible, I figured "Environment" made more sense.

### CODE REVIEW

**Comment by brettcannon** [comment]
Just because I want to mention these in a blog post, any idea how long until these will show up at https://pypi.org/classifiers/ ?

**Comment by merwok** [comment]
Depends on https://github.com/pypi/warehouse/pull/12874 I suppose

**Comment by di** [comment]
It's available now: https://pypi.org/classifiers/

**Comment by brettcannon** [comment]
Thanks!

**Pull request merged**
