### PR TITLE
Add JSON and JSON Schema classifiers.

### PR DESCRIPTION
**Pull request by Julian**
Request to add a new Trove classifier.

## The name of the classifier(s) you would like to add:

* `Topic :: Internet :: JSON` for [JSON](https://www.json.org/json-en.html)
* `Topic :: Internet :: JSON :: JSON Schema` for [JSON Schema](https://json-schema.org/) underneath it

## Why do you want to add this classifier?
No classifier currently collects JSON-adjacent projects despite their ubiquity.
JSON Schema is, thankfully, also quite large at this point, and tooling both within the JSON Schema ecosystem but also in the Open API and Async API ecosystem would likely use the classifier.

I'm not sure if [these guidelines](https://github.com/pypa/trove-classifiers/issues/121#issuecomment-1297351495) are specific to `Framework` classifiers or whether they'd apply here. I can of course speak for [myself](https://github.com/python-jsonschema/jsonschema) on wanting to use these in multiple libraries, but if there's a need to drum up more support obviously let me know! My assumption is certainly that one could find 10 or more for JSON and I'd be surprised if that wasn't the case for the `JSON Schema` specific one as well.

## Where does this belong?

There's `Topic :: Text Processing :: Markup :: XML` currently for XML, which I think is the closest existing classifier, though it seems equally awkward (as `Topic :: Internet`) to put JSON in that category. If there was a `Topic :: Data Formats` or a `Topic :: Specifications` perhaps one of those would seem decent places, but that's obviously an invasive kind of thing.

### CODE REVIEW

**Comment by di** [comment]
I think this makes sense to align more closely with classifiers like `Topic :: Text Processing :: Markup :: XML`. Maybe something like:

* `Topic :: File Formats :: JSON`
* `Topic :: File Formats :: JSON :: JSON Schema `

?

**Comment by Julian** [comment]
Cool, that certainly makes sense, as I say I agree! Just wanted to make sure I wasn't being presumptuous about creating new second-level categories without hearing you were up for it.

Do you think we should "move" / "deprecate" / "add" any existing ones under there if added? I.e. `Topic :: File Formats :: XML` or `Topic :: File Formats :: LaTeX`?

**Comment by di** [comment]
🤷 I think they're so infrequently used it probably doesn't matter? We can always revisit that later.

**Comment by Julian** [comment]
Works for me. Moved.

**Review by di — APPROVED** [review]
Thanks!

**Pull request merged**
