### PR TITLE
Add the 'Framework :: cocotb' classifier

### PR DESCRIPTION
**Pull request by eric-wieser**
## The name of the classifier(s) you would like to add:

* `Framework :: cocotb`

## Why do you want to add this classifier?

cocotb has an ecosystem of domain specific libraries built on top of it, some of which are listed on our [further resources page](https://github.com/cocotb/cocotb/wiki/Further-Resources#extension-modules-cocotbext) (and the section below that link). We believe a classifier would help with discoverability of these packages. `Topic :: Scientific/Engineering :: Electronic Design Automation (EDA)` does not fulfill this need as there are many non-cocotb EDA packages.

### CODE REVIEW

**Comment by jamadden** [comment]
Hi! Thanks for the well written request. The PyPI moderators have a few guidelines for the creation of new `Framework` classifiers. Because removing classifiers is very difficult, and the longer the classifier list gets the harder it is to browse, the bar to add new ones is relatively high. Currently, we have these guidelines:

* New `Framework` classifiers may be created if they are "notable;" and 
* They will be of immediate use to existing projects (in other words, no creating classifiers simply in anticipation of future uses)

We understand that "notability" is subjective and we'd appreciate help judging that; responses to the next guideline help.

As to the other guideline ('immediate use to existing projects'), the best way to demonstrate it is to have *10* (or more) other *project maintainers* submit comments on the requesting issue about their desire to use the classifier on their already-published project.

We appreciate any help gathering this information.

**Comment by themperek** [comment]
I would add it to https://pypi.org/project/cocotb-test/ if it existed.

**Comment by mballance** [comment]
I would add the tag to the following packages:
- https://pypi.org/project/pyvsc/
- https://pypi.org/project/pybfms/
- https://pypi.org/project/pybfms-generic-sram/

**Comment by sTiKyt** [comment]
There are 4450 results in GitHub published code saying "cocotb"
https://github.com/search?q=cocotb&type=code

**Comment by alexforencich** [comment]
I would apply it to the following projects:

https://github.com/alexforencich/cocotbext-axi (on pypi: https://pypi.org/project/cocotbext-axi/)
https://github.com/alexforencich/cocotbext-eth (in development)
https://github.com/alexforencich/cocotbext-pcie (in development)

and likely more in the future.

**Comment by eric-wieser** [comment]
@di, I don't understand why you changed the sort order here

**Comment by di** [comment]
This is currently sorted lexicographically, which takes case into account. It arguably shouldn't be, I'd accept a PR that fixes this for all the classifiers.

**Comment by eric-wieser** [comment]
Thanks for the merge, anyway!

**Comment by cmarqu** [comment]
@di Apparently because the JupyterLab classifier (#72) went in the same day, the upload of this failed because of the same version number: https://github.com/pypa/trove-classifiers/runs/3245694917#step:9:21

A quick fix would be nice; we advertised this classifier to our extension developers who now find that their packages are not getting accepted.

**Comment by di** [comment]
@cmarqu Thanks, I released it and merged https://github.com/pypa/warehouse/pull/9882, so this is available now.

**Comment by alexforencich** [comment]
Presumably it cannot be used until it appears on https://pypi.org/pypi?%3Aaction=list_classifiers, correct?  (used as in pypi does not reject uploading packages with the classifier)

**Comment by alexforencich** [comment]
Ah, it's there now.  Nice!

**Comment by cmarqu** [comment]
@alexforencich It just appeared there for me.

**Pull request merged**
