### PR TITLE
Add Django major-version trove classifiers.

### PR DESCRIPTION
**Pull request by FlipperPA**
Request to add a new Trove classifier.

## The name of the classifier(s) you would like to add:

* `Framework :: Django :: 1`
* `Framework :: Django :: 2`
* `Framework :: Django :: 3`
* `Framework :: Django :: 4`

## Why do you want to add this classifier?

Let's include Django major-version-only trove classifiers, to mimic Python's own trove classifiers.  Especially now that Django is following semver, it will be nice for those of us with packages in the ecosystem to just include what major version we support. Thanks!

### CODE REVIEW

**Comment by di** [comment]
👋 Hi @FlipperPA. Does it make sense to add `Framework :: Django :: <N> :: Only` as well?

**Comment by FlipperPA** [comment]
@di If you'd like to for consistency, I'd be happy to, but I can't think of any Django packages that would be quite that restrictive like the difference between Python 2 and 3 required. Great to see you, my friend! Let's grab lunch some time!

**Comment by di** [comment]
This will be available once this project releases (happens w/in 24 hours) and once the dependency is upgraded on PyPI.

**Comment by FlipperPA** [comment]
Thank you, @di - very much appreciated!

**Pull request merged**
