### PR TITLE
Add Django :: 4.0 classifier.

### PR DESCRIPTION
**Pull request by felixxm**
Request to add a new Trove classifier.

* `Framework :: Django :: 4.0`

## Why do you want to add this classifier?

Django 4.0 alpha was released on September 21, 2021. See: https://www.djangoproject.com/weblog/2021/sep/21/django-40-alpha-1-released/

### CODE REVIEW

**Comment by di** [comment]
This will be available after the new release is pulled into PyPI.

**Comment by carltongibson** [comment]
Thanks @di! 

> ...after the new release is pulled into PyPI.

Can I ask, is there a way to know when that is? (Sorry if that should be apparent. 😬)

**Comment by di** [comment]
There will be a PR like https://github.com/pypa/warehouse/pull/10076 in about 24 hours, once it's merged the classifier will be available.

**Comment by carltongibson** [comment]
@di Super. I shall keep the eye out for that. Thanks for the help!

**Pull request merged**
