### PR TITLE
Add "Programming Language :: Kotlin" classifier

### LINKED ISSUE #41: Request "Programming Language :: Kotlin" trove classifier
Hello! There is a Kotlin programming language, which became quite popular nowadays.

Please add **Programming Language :: Kotlin** classifier!

This is a first package which should get this classifier: https://pypi.org/project/kotlin-jupyter-kernel/

### PR DESCRIPTION
**Pull request by ileasile**
Request to add a new Trove classifier. Closes #41

## The name of the classifier(s) you would like to add:

* `Programming Language :: Kotlin`

## Why do you want to add this classifier?
Kotlin is a quite popular language, and also [this particular package](https://pypi.org/project/kotlin-jupyter-kernel/) needs it now.

### CODE REVIEW

**Comment by di** [comment]
Thanks!

**Comment by ileasile** [comment]
@di thank you! How long does it take a new classifier to appear on the web page with classifiers and in pypa "database"?

**Comment by di** [comment]
This project will go through a release cycle (which happens every 24 hours) and then the new dependency needs pulled into pypa/warehouse. So probably about 24-48 hours, but there are humans in the loop.

**Comment by ileasile** [comment]
This classifier is still not availible on https://pypi.org/classifiers/. I don't know is it expected or not)

**Comment by di** [comment]
Thanks. I just merged https://github.com/pypa/warehouse/pull/8447 but our release automation is not currently working. Should be available soon, likely tomorrow.

**Pull request merged**
