### PR TITLE
Add Pydantic classifiers

### PR DESCRIPTION
**Pull request by hramezani**
Request to add a new Trove classifier.

## The name of the classifier(s) you would like to add:

* `Framework :: Pydantic`
* `Framework :: Pydantic :: 1`

## Why do you want to add this classifier?

There are a lot of projects using `Pydantic` like [FastAPI](https://github.com/tiangolo/fastapi)
Currently `Pydantic` is on `V1`. we are working on `V2`. That's why I've just added version 1

Pydantic issue link: https://github.com/pydantic/pydantic/issues/4935
CC: @samuelcolvin

### CODE REVIEW

**Comment by samuelcolvin** [comment]
LGTM, thanks @hramezani.

Only suggestion: should we add a classifier for V2 now, or wait for release?

**Comment by samuelcolvin** [comment]
As per https://github.com/pypa/trove-classifiers/issues/121#issuecomment-1297351495 looks like it might help to have comments from 10 package maintainers saying they would use this classifier. That should be very easy.

✋ I'll go first, as well as maintaining pydantic, I maintain a number of packages that have pydantic as a dependency and would use this classifier.

Also worth noting that there are 535 packages [listed](https://github.com/topics/pydantic) under the "pydantic" topic on GitHub.

**Comment by hramezani** [comment]
> LGTM, thanks @hramezani.
> 
> Only suggestion: should we add a classifier for V2 now, or wait for release?

let's do it after V2 release

**Comment by art049** [comment]
Nice, I would definitely use the classifier for [ODMantic](https://pypi.org/project/odmantic/) as well!

**Review by yezz123 — APPROVED** [review]
Amazing ❤️ , I would definitely use the classifier for [authx](https://pypi.org/project/authx/), [ormdantic](https://pypi.org/project/ormdantic/) as well!

**Comment by JohannesMessner** [comment]
Looks cool! We would use it for [DocArray](https://github.com/docarray/docarray) and [Jina](https://github.com/jina-ai/jina).

**Comment by tlambert03** [comment]
would use for a number of projects!  pydantic is a key part of a lot of my packages.

**Comment by tiangolo** [comment]
Would definitely use it for FastAPI and SQLModel 🤓🚀

**Comment by di** [comment]
Thanks all for your statements of support for this classifier. 🙂 

This will be available on PyPI once this repository makes an automated release, and after PyPI upgrades to the latest version of this dependency.

**Comment by samuelcolvin** [comment]
Great, thanks so much.

**Pull request merged**
