### PR TITLE
Request to add Framework :: napari trove classifier

### PR DESCRIPTION
**Pull request by jni**
Request to add a new Trove classifier.

## The name of the classifier(s) you would like to add:

* `Framework :: napari`

## Why do you want to add this classifier?

napari is a multidimensional image viewer for Python. It has a plugin framework, based on pytest's pluggy, that currently allows independently libraries to add new IO capabilities to napari. An IO plugin allows users to drag and drop a previously unsupported image file format into the viewer, or to save the current view to a new format.

We would like the trove classifier to be able to discover plugins on PyPI and allow users to install them from napari directly. The (pip-based) installation infrastructure already exists in napari, but currently the user must manually specify the name of the PyPI package they would like to install — they have no way to list all available plugins.

Here is a partial list of existing plugins on PyPI:

- [ome-zarr](https://pypi.org/project/ome-zarr/) by @will-moore and @joshmoore
- [aicsimageio](https://pypi.org/project/napari-aicsimageio/) by @JacksonMaxfield
- [napari-mrcfile-reader](https://pypi.org/project/napari-mrcfile-reader/) by @alisterburt
- [napari-ndtiffs](https://pypi.org/project/napari-ndtiffs/) by @tlambert03
- [napari-sentinel-zip](https://pypi.org/project/napari-sentinel-zip/) by @DragaDoncila
- [napari-mat-images](https://pypi.org/project/napari-mat-images/) by @hectormz
- [napari-brainreg](https://pypi.org/project/napari-brainreg/) by @adamltyson
- [napari-tifffile-reader](https://pypi.org/project/napari-tifffile-reader/) by @GenevieveBuckley
- [napari-svg](https://pypi.org/project/napari-svg/) by @sofroniewn
- [napari-dzi-zarr](https://pypi.org/project/napari-dzi-zarr/) by @manzt
- [PartSeg](https://pypi.org/project/PartSeg/) by @Czaki

Everyone tagged above (:wave:): if you could submit a comment of support in this issue, or at least thumbs-up this comment (or both!), it would help us help users discover your plugins! :blush: See [this comment](https://github.com/pypa/trove-classifiers/issues/20#issuecomment-609291342) by @pradyunsg (:wave:) for details.

In addition to the list above, we are soon going to expand the number of hook specifications we make available to developers (not just IO, but image processing hooks), so we expect the above list to continue growing. @quantumjot, @haesleinhuepf, and @guiwitz are among those who could probably attest to wanting to write napari processing plugins.

### CODE REVIEW

**Comment by alisterburt** [comment]
this would be fantastic! very much looking forward to the extra hook specifications too

**Comment by adamltyson** [comment]
Very happy to support this. I have two plugins so far, and discoverability will be key for the upcoming image processing plguins.

**Comment by manzt** [comment]
+1 - great idea to increase visibility / discoverability of plugins

**Comment by will-moore** [comment]
This would be great, thanks! 👍

**Comment by DragaDoncila** [comment]
This would be great - especially interested in the processing hook specs

**Comment by GenevieveBuckley** [comment]
Yes, this would definitely help with discoverability within our community. Thanks for proposing this @jni

**Comment by jamadden** [comment]
I was just coming here to add the standard template for Framework classifier requests, and I see that you already found it, *and* reached out to project maintainers! Thanks for doing the research! 

Given what I see here, I would agree that this would be of immediate use and seems notable. I would recommend the classifier for inclusion.

The next step would be to create a PR in this repository adding the classifier. Reference this issue ("fixes #53") in the commit message or PR comment so that the reviewers can see it.

**Comment by jamadden** [comment]
D'oh. I see that this is the PR. Sorry, I'm used to people opening issues before PRs.

**Review by jamadden — APPROVED** [review]

**Comment by jni** [comment]
Wow, that was quick! Thank you so much @jamadden (and @di!) for the one step review! 🎉

**Comment by Czaki** [comment]
When it will be accepted by pypi?

**Comment by jni** [comment]
@Czaki even though it doesn't yet appear in the [online list](https://pypi.org/classifiers/), the latest release of [`trove-classifiers`](https://pypi.org/project/trove-classifiers/), "Canonical source for classifiers on PyPI", includes it. I guess it just needs to propagate through various pipelines?

```
jni@beastie Sun Oct 25 17:50
 ~/projects/napari (master)
 $ pip install trove-classifiers
Collecting trove-classifiers
  Downloading trove_classifiers-2020.10.21-py3-none-any.whl (12 kB)
Installing collected packages: trove-classifiers
Successfully installed trove-classifiers-2020.10.21
(39)
jni@beastie Sun Oct 25 17:50
 ~/projects/napari (master)
 $ python
Python 3.9.0 | packaged by conda-forge | (default, Oct 14 2020, 22:56:29)
[Clang 10.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from trove_classifiers import classifiers
>>> 'Framework :: napari' in classifiers
True
```

**Comment by Czaki** [comment]
@jni I understand, but I try to upload a new version of PartSeg (an application which uses napari) with added this classifier and it was rejected. And I do not know If I should rather wait 1-2 days or postpone adding classifier until the next release.

**Comment by di** [comment]
This was deployed to PyPI in https://github.com/pypa/warehouse/pull/8737 and is now availalbe.

**Pull request merged**
