### PR TITLE
Added Framework::SEAMM classifier for the SEAMM environment.

### PR DESCRIPTION
**Pull request by paulsaxe**
Request to add a new Trove classifier.

## The name of the classifier(s) you would like to add:

* `Framework :: SEAMM`

## Why do you want to add this classifier?

SEAMM (Simulation Environment for Atomistic and Molecular Modeling, https://molssi-seamm.github.io) is a decentralized open-source framework being developed by the Molecular Sciences Software Institute (MolSSI, https://molssi.org), an institute at Virginia Tech funded by the National Science Foundation.

A unique classifier would allow the framework to programmatically locate plug-ins available at PyPi, allowing developers in the community to create and distribute plug-ins in a straightforward and robust fashion without the bottleneck of a central repository or database needing to be updated. There are currently about 18 plug-ins and 7 core projects for SEAMM; however, the computational chemistry and materials science community develops and maintains many hundreds if not thousands of computational codes, mainly in FORTRAN and C/C++, which can be integrated into SEAMM by creating plug-ins. Hence we expect (hope?) for several hundred projects using the classifier.

SEAMM is conceptually similar to AiiDA, which has a framework classifier. AiiDA predominantly serves the materials science community while SEAMM is broader, also serving the computational chemistry and biomolecular modeling communities.

### CODE REVIEW

**Review by dudss37 — APPROVED** [review]

**Comment by pradyunsg** [comment]
Hi! Thanks for the request. Because removing classifiers is very difficult, and the longer the classifier list gets the harder it is to browse, the bar to add new ones is relatively high. Currently, PyPI moderators primarily examine two guidelines for Framework classifiers:

- New Framework classifiers should be created if they are "notable" and
- They will be of immediate use to existing projects (in other words, no creating classifiers simply in anticipation of future uses)

We understand that "notability" is subjective and we'd appreciate help judging that; the information you've already provided goes a long way towards satisfying that.

As to the other guideline ('immediate use to existing projects'), the best way we've found to demonstrate that is to have 10 or more other project maintainers submit comments on the requesting issue about their desire to use the classifier. Is that something you could assist with?

**Comment by dudss37** [comment]
[]()

**Comment by dudss37** [comment]
- [ ]

**Comment by paulsaxe** [comment]
@pradyunsg Sorry for being slow to respond! I understand your points and agree totally. I am not sure what more I can say about notable, but it seems perfectly reasonable -- and a challenge to me -- to get about 10 other project maintainers to add their comments. So let me do that and get back to you then. At the moment I have a system working searching for specific keywords, which will carry us quite far until we can show that it makes sense to add a classifier, which of course is more robust than keywords.

**Comment by di** [comment]
Going to close this for now, but feel free to reopen if/when there are more projects here and a classifier makes more sense.

**Pull request closed without merging**
