### PR TITLE
Added commonly used programming languages.

### PR DESCRIPTION
**Pull request by nekokatt**
- Vlang
- Go
- Clojure
- Scala
- Groovy
- Dlang
- Elixir
- TypeScript
- Dart

Added POSIX shell, since Unix shell does not need to be run on Unix, so it is somewhat misleading for 
a Unix Shell project to target Windows (e.g. MINGW related tools?), for example. Haven't removed Unix shell
since that would be a breaking change for people.

Request to add a new Trove classifier.

- "Programming Language :: V"
- "Programming Language :: Go"
- "Programming Language :: Clojure"
- "Programming Language :: Scala"
- "Programming Language :: Groovy"
- "Programming Language :: D"
- "Programming Language :: Elixir"
- "Programming Language :: TypeScript"
- "Programming Language :: Dart"
- "Programming Language :: POSIX Shell"

## Why do you want to add this classifier?

These are commonly used programming languages, most are already widely used.

Posix shell has been added since tools like bash/dash which would fall under Unix shell do not necessarily need to be run on Unix to be valid.

### CODE REVIEW

**Comment by di** [comment]
Hi, thanks for the PR. We tend to prefer to add these when there's a demand for them, instead of trying to be comprehensive.

Is there a specific one of these that you'd like to publish a project with?

**Comment by McSinyx** [comment]
I'm sorry for the off-topic question, but how was this repo configured to only merge updated PR?  I notice this notice right below the CIs report on this page:

> This branch is out-of-date with the base branch

**Comment by di** [comment]
This is the "Require branches to be up to date before merging" setting, see #​7 here: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-required-status-checks

**Comment by McSinyx** [comment]
Thanks!

**Comment by nekokatt** [comment]
@di it was mainly for consistency, but that is understandable! Thanks for the reply :)

**Pull request closed without merging**
